### ISSUE TITLE
ImportError: cannot import name inplace_increment

### ISSUE THREAD

**Issue by SeekPoint** [luheng/deep_srl#15]
(.venv) ub16hp@UB16HP:~/ub16_prj/deep_srl$ bash scripts/run_train.sh 0
Traceback (most recent call last):
  File "python/train.py", line 4, in <module>
    from neural_srl.theano.tagger import BiLSTMTaggerModel
  File "/home/ub16hp/ub16_prj/deep_srl/python/neural_srl/theano/tagger.py", line 1, in <module>
    from optimizer import *
  File "/home/ub16hp/ub16_prj/deep_srl/python/neural_srl/theano/optimizer.py", line 2, in <module>
    import theano
  File "/home/ub16hp/ub16_prj/deep_srl/.venv/local/lib/python2.7/site-packages/theano/__init__.py", line 80, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/home/ub16hp/ub16_prj/deep_srl/.venv/local/lib/python2.7/site-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/home/ub16hp/ub16_prj/deep_srl/.venv/local/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
  File "/home/ub16hp/ub16_prj/deep_srl/.venv/local/lib/python2.7/site-packages/theano/tensor/__init__.py", line 9, in <module>
    from theano.tensor.subtensor import *
  File "/home/ub16hp/ub16_prj/deep_srl/.venv/local/lib/python2.7/site-packages/theano/tensor/subtensor.py", line 27, in <module>
    from cutils_ext.cutils_ext import inplace_increment
ImportError: cannot import name inplace_increment
(.venv) ub16hp@UB16HP:~/ub16_prj/deep_srl$

**Comment by A-lexsal** [comment]
Hello!Did you run it successfully?

**Comment by SeekPoint** [comment]
not yet

**Comment by A-lexsal** [comment]
I ran a simple example with her model, but I can't get the conll2005 dataset. Maybe your environment is wrong.
