### ISSUE TITLE
AssertionError 

### ISSUE THREAD

**Issue by Nasidiqi** [luheng/deep_srl#24]
i am recieving this error, any idea how to fix it?

Traceback (most recent call last):
  File "python/predict.py", line 227, in <module>
    evaluator.evaluate(predictions)
  File "/home/ubuntu/deep_srl-master/python/neural_srl/shared/evaluation.py", line 26, in evaluate
    self.compute_accuracy(predictions)
  File "/home/ubuntu/deep_srl-master/python/neural_srl/shared/evaluation.py", line 97, in compute_accuracy
    print_to_conll(self.pred_labels, self.pred_props_file, temp_output)
  File "/home/ubuntu/deep_srl-master/python/neural_srl/shared/conll_utils.py", line 45, in print_to_conll
    print_sentence_to_conll(fout, tokens_buf, pred_labels[seq_ptr:seq_ptr+num_props_for_sentence])
  File "/home/ubuntu/deep_srl-master/python/neural_srl/shared/conll_utils.py", line 26, in print_sentence_to_conll
    assert len(label_column) == len(tokens)
AssertionError

**Comment by Bamboo-TNLP** [comment]
Is the problem solved?

**Comment by cjj-sunshine** [comment]
> Is the problem solved?

Has the problem been resolved? Looking forward to your reply!
